export type ADD_TODO_TYPE = 'ADD_TODO';
export type DELETE_TODO_TYPE = 'DELETE_TODO';
export type TOGGLE_TODO_TYPE = 'TOGGLE_TODO';

export const ADD_TODO : ADD_TODO_TYPE = 'ADD_TODO';
export const DELETE_TODO : DELETE_TODO_TYPE = 'DELETE_TODO';
export const TOGGLE_TODO : TOGGLE_TODO_TYPE = 'TOGGLE_TODO';